### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by shreyaslad** [Sidthecoder/Karat#1]
Can u invite me to Karat. For some reason, ur not pooping up on the list of collaborators on Impact

**Comment by shreyaslad** [comment]
Whoops... Popping, not pooping

**Comment by shreyaslad** [comment]
🤣

**Comment by Sidthecoder** [comment]
Invited

**Comment by ghost** [comment]
OMG 🤣

**Comment by ghost** [comment]
Oh dude shreyas, remember, you removed Sid from impact.

**Comment by ghost** [comment]
Hey can we close this
