### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by ghost** [Sidthecoder/Karat#2]
The build for this repo is not proper. Try to create an `src` folder. Put all of the CSS files in that. I will then use a gulpfile.js to concatenate those files into two files: `main.css` and `main.min.css`. So the structure should look like this:

- dist
    - empty (For now until I make the main.css and main.min.css files)
- public
    - src1.css
    - src2.css
    - src3.css
- LICENSE
- README.md
- package.JSON
- gulpfile.js

Once I concatenate the files and minify them, then the dist folder will have main.css and main.min.css. Also one more issue is that the main.css is minified. If you add me I will fix this all in a jiffy. Thanks!

**Comment by Sidthecoder** [comment]
Uh? You do it?
